import { Category, Technique } from './types';

export const techniques: Technique[] = [
  // --- Structuring ---
  {
    id: 'CL10',
    code: 'CL10',
    title: 'Clarify Context',
    simpleExplanation: 'Set the scene so the AI knows its role and audience.',
    fullExplanation: 'Tell the model who it should be and who it is talking to. This gives correct tone + depth.',
    example: 'Act as a senior software architect explaining microservices to a junior developer.',
    category: Category.Structuring,
    tags: ['Context', 'Role', 'Setup'],
  },
  {
    id: 'CO10',
    code: 'CO10',
    title: 'Ensure Coherence',
    simpleExplanation: 'Make the answer flow in a clear order.',
    fullExplanation: 'Ask the model to organize the answer logically (steps, headings, sequence).',
    example: 'Explain the water cycle. Organize the response chronologically starting from evaporation.',
    category: Category.Structuring,
    tags: ['Flow', 'Logic', 'Order'],
  },
  {
    id: 'SB10',
    code: 'SB10',
    title: 'Bullet Summary',
    simpleExplanation: 'Force the answer into clean, readable bullets.',
    fullExplanation: 'Ask the model to output in bullet points for clarity.',
    example: 'Summarize the meeting notes into 5 key bullet points.',
    category: Category.Structuring,
    tags: ['Summary', 'Brevity', 'Format'],
  },
  {
    id: 'JX10',
    code: 'JX10',
    title: 'JSON Structuring',
    simpleExplanation: 'Force the AI to give structured data in JSON format.',
    fullExplanation: 'Tell the model to output valid JSON only, useful for code integration.',
    example: 'List 5 fruit types with their colors and average weight in JSON format.',
    category: Category.Structuring,
    tags: ['Code', 'Data', 'Integration'],
  },
  {
    id: 'TB10',
    code: 'TB10',
    title: 'Tabular Format',
    simpleExplanation: 'Make the answer appear as a table for easy comparison.',
    fullExplanation: 'Ask for a table using markdown syntax.',
    example: 'Compare React, Vue, and Angular in a table with columns for: Learning Curve, Popularity, and Key Features.',
    category: Category.Structuring,
    tags: ['Visual', 'Comparison', 'Data'],
  },
  {
    id: 'MD10',
    code: 'MD10',
    title: 'Markdown Structuring',
    simpleExplanation: 'Make the answer well-formatted using markdown.',
    fullExplanation: 'Tell the model to use headings, bullets, bold text, and code blocks.',
    example: 'Write a blog post about SEO using H1, H2, and bold text for keywords.',
    category: Category.Structuring,
    tags: ['Format', 'Blog', 'Readability'],
  },
  {
    id: 'DF10',
    code: 'DF10',
    title: 'Data/Chart Format',
    simpleExplanation: 'Output data in a chart-friendly or table-friendly format.',
    fullExplanation: 'Ask for CSV/JSON or ASCII charts for data visualization.',
    example: 'Generate a CSV list of monthly sales data for the last year.',
    category: Category.Structuring,
    tags: ['Data', 'Analysis', 'Export'],
  },
  {
    id: 'SB20',
    code: 'SB20',
    title: 'Step-Back Structuring',
    simpleExplanation: 'AI plans the structure first, then writes the content.',
    fullExplanation: 'First ask for an outline → then a detailed answer based on that outline.',
    example: 'Create a detailed outline for a history essay, then write the essay based on the outline.',
    category: Category.Structuring,
    tags: ['Planning', 'Long-form', 'Outline'],
  },

  // --- Reasoning ---
  {
    id: 'RE10',
    code: 'RE10',
    title: 'Step-by-step Reasoning',
    simpleExplanation: 'Make the AI show its reasoning clearly and step-by-step.',
    fullExplanation: 'Tell the model to think slowly and explain each step (Chain of Thought).',
    example: 'Solve this math problem, but explain each step of your calculation before giving the final answer.',
    category: Category.Reasoning,
    tags: ['Logic', 'Math', 'Deep Dive'],
  },
  {
    id: 'AN10',
    code: 'AN10',
    title: 'Use Analogies',
    simpleExplanation: 'Explain X by comparing it to something familiar.',
    fullExplanation: 'Ask the model to explain the concept with a comparison.',
    example: 'Explain how a CPU works using an analogy of a professional kitchen.',
    category: Category.Reasoning,
    tags: ['Learning', 'Simplification', 'Teaching'],
  },
  {
    id: 'MP10',
    code: 'MP10',
    title: 'Multiple Perspectives',
    simpleExplanation: 'Make the answer show both sides of an issue.',
    fullExplanation: 'Ask for pros/cons or viewpoints from different people or stakeholders.',
    example: 'Analyze the impact of remote work from the perspective of an employee and an employer.',
    category: Category.Reasoning,
    tags: ['Debate', 'Analysis', 'Balanced'],
  },
  {
    id: 'TT20',
    code: 'TT20',
    title: 'Tree-of-Thoughts',
    simpleExplanation: 'AI thinks in branches and selects the strongest approach.',
    fullExplanation: 'AI explores multiple solution paths and picks the best one.',
    example: 'Propose three different marketing strategies for a new coffee shop, evaluate each, and choose the best one.',
    category: Category.Reasoning,
    tags: ['Strategy', 'Complex Problem', 'Evaluation'],
  },
  {
    id: 'DA20',
    code: 'DA20',
    title: 'Devil’s Advocate',
    simpleExplanation: 'Force the AI to challenge the idea and find weaknesses.',
    fullExplanation: 'AI argues against a claim to test its strength.',
    example: 'I believe nuclear energy is the future. Play devil\'s advocate and argue against this.',
    category: Category.Reasoning,
    tags: ['Critical Thinking', 'Debate', 'Stress Test'],
  },
  {
    id: 'CD20',
    code: 'CD20',
    title: 'Contradiction Detection',
    simpleExplanation: 'AI scans the answer for contradictions.',
    fullExplanation: 'AI checks for conflicting statements within a text.',
    example: 'Review the following witness statement and identify any internal contradictions.',
    category: Category.Reasoning,
    tags: ['Logic', 'Review', 'Analysis'],
  },
  {
    id: 'VS20',
    code: 'VS20',
    title: 'Viewpoint Synthesis',
    simpleExplanation: 'AI merges multiple viewpoints into one balanced answer.',
    fullExplanation: 'AI summarizes conflicting views → then combines them.',
    example: 'Synthesize the arguments for and against Universal Basic Income into a unified policy recommendation.',
    category: Category.Reasoning,
    tags: ['Synthesis', 'Summary', 'Conclusion'],
  },
  {
    id: 'EC20',
    code: 'EC20',
    title: 'Edge-Case Exploration',
    simpleExplanation: 'Test how the answer changes in rare or extreme cases.',
    fullExplanation: 'AI considers unusual or extreme scenarios.',
    example: 'Design a login system, but specifically focus on edge cases like network failure during authentication.',
    category: Category.Reasoning,
    tags: ['Testing', 'Robustness', 'Engineering'],
  },
  {
    id: 'CR20',
    code: 'CR20',
    title: 'Criteria-based Ranking',
    simpleExplanation: 'AI ranks choices based on measurable factors.',
    fullExplanation: 'List criteria → Score options → Rank them.',
    example: 'Rank these 5 laptops for video editing based on GPU, RAM, and Screen Accuracy.',
    category: Category.Reasoning,
    tags: ['Decision', 'Ranking', 'Scoring'],
  },

  // --- Creative ---
  {
    id: 'FR10',
    code: 'FR10',
    title: 'Human-like Tone',
    simpleExplanation: 'Make the AI sound warm and conversational.',
    fullExplanation: 'Tell the model to write in a natural, friendly voice.',
    example: 'Write a rejection email for a job candidate, but make it extremely warm and encouraging.',
    category: Category.Creative,
    tags: ['Tone', 'Writing', 'Soft Skills'],
  },
  {
    id: 'PS10',
    code: 'PS10',
    title: 'Persona / Role-play',
    simpleExplanation: 'Tell the AI to act like a specific expert or character.',
    fullExplanation: 'Assign a character (teacher, chef, doctor, etc.).',
    example: 'Act as a Michelin-star chef describing your signature dish.',
    category: Category.Creative,
    tags: ['Character', 'Fiction', 'Expertise'],
  },
  {
    id: 'ST10',
    code: 'ST10',
    title: 'Storytelling Format',
    simpleExplanation: 'Turn the concept into a simple, memorable story.',
    fullExplanation: 'Ask for explanation through a short story.',
    example: 'Explain the concept of inflation by telling a story about a village that uses seashells as money.',
    category: Category.Creative,
    tags: ['Narrative', 'Education', 'Engagement'],
  },
  {
    id: 'IM10',
    code: 'IM10',
    title: 'Vivid Imagery',
    simpleExplanation: 'Ask the AI to paint a picture with words.',
    fullExplanation: 'Request creative, descriptive language or metaphors.',
    example: 'Describe a futuristic city at sunset using sensory details.',
    category: Category.Creative,
    tags: ['Descriptive', 'Writing', 'Art'],
  },
  {
    id: 'EP20',
    code: 'EP20',
    title: 'Expert Persona Emulation',
    simpleExplanation: 'AI uses expert-level reasoning and vocabulary.',
    fullExplanation: 'Model behaves like a highly qualified expert in a niche field.',
    example: 'Critique this legal contract acting as a veteran corporate lawyer with 20 years of experience.',
    category: Category.Creative,
    tags: ['Professional', 'Deep Knowledge', 'Simulation'],
  },
  {
    id: 'MC20',
    code: 'MC20',
    title: 'Multi-Modal Context',
    simpleExplanation: 'AI uses both text and described visuals for analysis.',
    fullExplanation: 'AI incorporates visual/chart descriptions into reasoning.',
    example: 'Based on this description of a scatter plot showing rising temperatures, predict future trends.',
    category: Category.Creative,
    tags: ['Visuals', 'Complex', 'Analysis'],
  },
  {
    id: 'DI10',
    code: 'DI10',
    title: 'Diagrammatic Visualization',
    simpleExplanation: 'Tell the AI to produce a text-based diagram.',
    fullExplanation: 'Ask the AI to create diagrams using Mermaid or PlantUML.',
    example: 'Create a Mermaid JS sequence diagram showing a user login flow.',
    category: Category.Creative,
    tags: ['Code', 'Visual', 'Diagram'],
  },

  // --- Validation & Constraints ---
  {
    id: 'CN10',
    code: 'CN10',
    title: 'Be Concise',
    simpleExplanation: 'Force the AI to remove fluff and keep only the important points.',
    fullExplanation: 'Tell the model to keep it short and focused using bullets or limits.',
    example: 'Explain quantum entanglement in one sentence.',
    category: Category.Validation,
    tags: ['Brevity', 'Focus', 'Editing'],
  },
  {
    id: 'SP10',
    code: 'SP10',
    title: 'Simplify Language',
    simpleExplanation: 'Ask the AI to explain it in simple, non-technical language.',
    fullExplanation: 'Tell the model to use easy words, simple explanations, or analogies.',
    example: 'Explain blockchain to a 5-year-old.',
    category: Category.Validation,
    tags: ['ELI5', 'Teaching', 'Clarity'],
  },
  {
    id: 'EX10',
    code: 'EX10',
    title: 'Provide Examples',
    simpleExplanation: 'Show a sample so the model knows exactly how to answer.',
    fullExplanation: 'Give an example of the answer format so the AI copies the style.',
    example: 'Generate a tweet. Example: "Just launched my new app! 🚀 #coding".',
    category: Category.Validation,
    tags: ['Few-shot', 'Format', 'Guide'],
  },
  {
    id: 'FS10',
    code: 'FS10',
    title: 'Few-shot Prompting',
    simpleExplanation: 'Teach the AI the pattern using a few examples.',
    fullExplanation: 'Provide 1–3 example Q&A pairs before your real question.',
    example: 'Translate to Spanish. Hello -> Hola. Goodbye -> Adios. Good morning ->',
    category: Category.Validation,
    tags: ['Training', 'Pattern', 'Accuracy'],
  },
  {
    id: 'TC10',
    code: 'TC10',
    title: 'Tone Control',
    simpleExplanation: 'Choose how the AI should sound.',
    fullExplanation: 'Specify the tone (formal, friendly, academic, etc.).',
    example: 'Rewrite this angry customer complaint in a polite, professional tone.',
    category: Category.Validation,
    tags: ['Style', 'Voice', 'Adjustment'],
  },
  {
    id: 'WL10',
    code: 'WL10',
    title: 'Word/Length Limit',
    simpleExplanation: 'Strictly control how long the answer can be.',
    fullExplanation: 'Set a word or sentence limit.',
    example: 'Write a biography of Tesla in exactly 50 words.',
    category: Category.Validation,
    tags: ['Constraint', 'Length', 'Precision'],
  },
  {
    id: 'CN10-Strict',
    code: 'CN10+',
    title: 'Strict Constraints',
    simpleExplanation: 'Restrict the AI to follow exact rules with no extra text.',
    fullExplanation: 'Give hard rules like "Yes or No only."',
    example: 'Is the number 5 prime? Answer with "Yes" or "No" only.',
    category: Category.Validation,
    tags: ['Rules', 'Logic', 'Binary'],
  },
  {
    id: 'FC10',
    code: 'FC10',
    title: 'Fixed-Choice Classification',
    simpleExplanation: 'Make the answer be only one category from your list.',
    fullExplanation: 'Force the model to select one option from a list.',
    example: 'Classify this email as: Spam, Urgent, or General. "Buy cheap meds now!"',
    category: Category.Validation,
    tags: ['Classification', 'Data', 'Filtering'],
  },
  {
    id: 'RV10',
    code: 'RV10',
    title: 'Self-Review & Revision',
    simpleExplanation: 'AI checks its own answer for mistakes, then fixes them.',
    fullExplanation: 'Tell the model to review its own answer and improve it.',
    example: 'Write code to sort a list. Then review it for bugs and rewrite if necessary.',
    category: Category.Validation,
    tags: ['Quality', 'Code', 'Iterative'],
  },
  {
    id: 'SC20',
    code: 'SC20',
    title: 'Self-Consistency',
    simpleExplanation: 'AI compares its own answers and selects the best one.',
    fullExplanation: 'Model generates multiple answers → picks the most consistent.',
    example: 'Solve this riddle. Generate three possible answers and choose the one that makes the most sense.',
    category: Category.Validation,
    tags: ['Accuracy', 'Logic', 'Reliability'],
  },
  {
    id: 'CV20',
    code: 'CV20',
    title: 'Chain-of-Verification',
    simpleExplanation: 'AI asks itself questions to check accuracy, then corrects.',
    fullExplanation: 'AI verifies its own answer with follow-up questions.',
    example: 'Write a biography of Lincoln. Then fact-check dates and events mentioned.',
    category: Category.Validation,
    tags: ['Fact-check', 'Truth', 'Verification'],
  },
  {
    id: 'CT20',
    code: 'CT20',
    title: 'Comparative Table Analysis',
    simpleExplanation: 'Side-by-side comparison using clear criteria.',
    fullExplanation: 'AI compares items using a structured table.',
    example: 'Compare the iPhone 15 and Samsung S24 in a table focusing on Camera, Battery, and Price.',
    category: Category.Validation,
    tags: ['Comparison', 'Data', 'Shopping'],
  },
];